GRANT SELECT, INSERT, UPDATE, DELETE, FILE, EXECUTE, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON *.* TO 'cmms_user'@'localhost' IDENTIFIED BY PASSWORD '*807BB985AA00E5696618B3F926295C190C68180C';

GRANT SELECT, INSERT, UPDATE, DELETE, EXECUTE, CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `cmms`.* TO 'cmms_user'@'localhost';